// Authentication
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';

// Contact actions
export const UPDATE_CONTACT_INFORMATION = 'UPDATE_CONTACT_INFORMATION';
export const REMOVE_CONTACT_INFORMATION = 'REMOVE_CONTACT_INFORMATION';

// profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const UPDATE_COURSE_NAME = 'UPATE_COURSE_NAME';

// Notifications
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// Units
export const UPDATE_UNITS = 'UPDATE_UNITS';
export const REMOVE_UNIT = 'REMOVE_UNIT';
export const REMOVE_UNITS = 'REMOVE_UNITS';
export const REMOVE_UNIT_ROW = 'REMOVE_UNIT_ROW';
export const INSERT_UNIT_ROW = 'INSERT_UNIT_ROW';
export const UPDATE_UNIT_ROW_CONTENT = 'UPDATE_UNIT_ROW_CONTENT';
export const UPDATE_UNIT_TITLE = 'UPDATE_UNIT_TITLE';
export const ADD_UNIT_TABLE = 'ADD_UNIT_TABLE';
export const REMOVE_UNIT_TABLE = 'REMOVE_UNIT_TABLE';

// Years
export const UPDATE_YEARS = 'UPDATE_YEARS';
export const INSERT_YEAR = 'INSERT_YEAR';
export const UPDATE_YEAR_TITLE = 'UPDATE_YEAR_TITLE';
export const REMOVE_YEAR = 'REMOVE_YEAR';
