const courseYears = [
  '1',
  '2',
  '3',
  '4',
  '5+',
];

const courseNames = [
  'Accounting & Finance',
  'Aeronautical & Manufacturing Engineering',
  'Agriculture & Forestry',
  'American Studies',
  'Anatomy & Physiology',
  'Anthropology',
  'Archaeology',
  'Architecture',
  'Art & Design',
  'Aural & Oral Sciences',
  'Biological Sciences',
  'Building',
  'Business & Management Studies',
  'Celtic Studies',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Classics & Ancient History',
  'Communication & Media Studies',
  'Complementary Medicine',
  'Computer Science',
  'Counselling',
  'Creative Writing',
  'Criminology',
  'Dentistry',
  'Drama, Dance & Cinematics',
  'East & South Asian Studies',
  'Economics',
  'Education',
  'Electrical & Electronic Engineering',
  'English',
  'Fashion',
  'Film Making',
  'Food Science',
  'Forensic Science',
  'French',
  'Geography & Environmental Sciences',
  'Geology',
  'General Engineering',
  'German',
  'History',
  'History of Art, Architecture & Design',
  'Hospitality, Leisure, Recreation & Tourism',
  'Iberian Languages/Hispanic Studies',
  'Italian',
  'Land & Property Management',
  'Law',
  'Librarianship & Information Management',
  'Linguistics',
  'Marketing',
  'Materials Technology',
  'Mathematics',
  'Mechanical Engineering',
  'Medical Technology',
  'Medicine',
  'Middle Eastern & African Studies',
  'Music',
  'Nursing',
  'Occupational Therapy',
  'Optometry, Ophthalmology & Orthoptics',
  'Pharmacology & Pharmacy',
  'Philosophy',
  'Physics and Astronomy',
  'Physiotherapy',
  'Politics',
  'Psychology',
  'Robotics',
  'Russian & East European Languages',
  'Social Policy',
  'Social Work',
  'Sociology',
  'Sports Science',
  'Theology & Religious Studies',
  'Town & Country Planning and Landscape Design',
  'Veterinary Medicine',
  'Youth Work',
  'Other',
];

const unitedKingdomUniversities = [
  'University of Aberdeen',
  'Abertay University',
  'Aberystwyth University',
  'Anglia Ruskin University, Cambridge ',
  'Arden University',
  'Aston University, Birmingham',
  'Bangor University',
  'University of Bath',
  'Bath Spa University',
  'University of Bedfordshire, Luton and Bedford',
  'University of Birmingham',
  'Birmingham City University',
  'University College Birmingham',
  'Bishop Grosseteste University, Lincoln',
  'University of Bolton',
  'The Arts University Bournemouth',
  'Bournemouth University',
  'BPP University',
  'University of Bradford',
  'University of Brighton',
  'University of Bristol',
  'Brunel University, Uxbridge and London',
  'University of Buckingham, private',
  'Buckinghamshire New University, High Wycombe',
  'University of Cambridge',
  'Canterbury Christ Church University',
  'Cardiff Metropolitan University',
  'Cardiff University',
  'University of Chester',
  'University of Chichester',
  'Coventry University',
  'Cranfield University',
  'University for the Creative Arts',
  'University of Cumbria',
  'De Montfort University, Leicester',
  'University of Derby',
  'University of Dundee',
  'Durham University',
  'University of East Anglia, Norwich',
  'University of East London',
  'Edge Hill University, [[Ormskirk, Lancashire',
  'University of Edinburgh',
  'Edinburgh Napier University',
  'University of Essex, Colchester and Southend-on-Sea',
  'University of Exeter',
  'Falmouth University',
  'University of Glasgow',
  'Glasgow Caledonian University',
  'University of Gloucestershire, Cheltenham, Gloucester and London',
  'Glyndŵr University, Wrexham',
  'University of Greenwich',
  'Harper Adams University, Newport, Shropshire',
  'Heriot-Watt University, Edinburgh and Galashiels',
  'University of Hertfordshire, Hatfield',
  'University of the Highlands & Islands',
  'University of Huddersfield, Huddersfield & Barnsley',
  'University of Hull, Hull and Scarborough',
  'Imperial College London',
  'Keele University, Staffordshire',
  'University of Kent, Canterbury and Medway',
  'Kingston University',
  'University of Central Lancashire,',
  'Lancaster University',
  'University of Leeds',
  'Leeds Arts University',
  'Leeds Beckett University',
  'Leeds Trinity University',
  'University of Leicester',
  'University of Lincoln, Lincoln, Hull, Riseholme and Holbeach',
  'University of Liverpool',
  'Liverpool Hope University',
  'Liverpool John Moores University',
  'University of London ',
  'Birkbeck, University of London',
  'City, University of London',
  'Royal Central School of Speech and Drama',
  'Courtauld Institute of Art',
  'Goldsmiths, University of London',
  'Heythrop College',
  'Institute of Cancer Research',
  'London Business School',
  'London School of Economics',
  'London School of Hygiene and Tropical Medicine',
  'Queen Mary, University of London',
  'Royal Academy of Music',
  'Royal Holloway, University of London, Egham ',
  'Royal Veterinary College',
  'St George\'s, University of London',
  'School of Oriental and African Studies (SOAS)',
  'University College London (UCL) ',
  'London Metropolitan University',
  'London South Bank University',
  'Loughborough University',
  'University of Manchester',
  'Manchester Metropolitan University',
  'Middlesex University, London',
  'Newcastle University',
  'Newman University, Birmingham|Newman University, Birmingham',
  'University of Northampton',
  'Northumbria University, Newcastle upon Tyne',
  'Norwich University of the Arts',
  'University of Nottingham',
  'Nottingham Trent University',
  'The Open University, Milton Keynes',
  'University of Oxford',
  'Oxford Brookes University',
  'University of Plymouth',
  'University of Portsmouth',
  'Queen Margaret University, Edinburgh',
  'Queen\'s University Belfast',
  'University of Reading',
  'Regent\'s University London',
  'The Robert Gordon University, Aberdeen',
  'Roehampton University, London',
  'Royal Agricultural University, [[Cirencester',
  'University of Salford',
  'University of Sheffield',
  'Sheffield Hallam University',
  'University of South Wales',
  'University of Southampton',
  'Southampton Solent University',
  'University of St Andrews',
  'University of St Mark & St John, [[Plymouth',
  'St Mary\'s University, Twickenham',
  'Staffordshire University, Stoke-on-Trent, Stafford and Lichfield',
  'University of Stirling, Bridge of Allan',
  'University of Strathclyde, Glasgow',
  'University of Suffolk',
  'University of Sunderland',
  'University of Surrey, Guildford',
  'University of Sussex, Falmer and Brighton',
  'Swansea University',
  'Teesside University, Middlesbrough and Darlington',
  'University of the Arts London',
  'Ulster University, Coleraine, Jordanstown, Magee and Belfast',
  'University of Law',
  'University of Wales (will merge with UWTSD in 2017)',
  'University of Wales, Trinity Saint David (UWTSD), Lampeter, Carmarthen and Swansea',
  'University of Warwick, Coventry',
  'University of the West of England, Bristol',
  'University of the West of Scotland, Paisley, Hamilton, Ayr & Dumfries',
  'University of West London, Ealing and Brentford',
  'University of Westminster, London',
  'University of Winchester',
  'University of Wolverhampton',
  'University of Worcester',
  'University of York',
  'York St John University',
  'Other',
];

const universitiesList = unitedKingdomUniversities;

export {
  courseYears,
  courseNames,
  universitiesList,
};
