// Authentication
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';

// Contact actions
export const UPDATE_CONTACT_INFORMATION = 'UPDATE_CONTACT_INFORMATION';
export const REMOVE_CONTACT_INFORMATION = 'REMOVE_CONTACT_INFORMATION';

// profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';

// Notifications
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';

// Units
export const UPDATE_UNITS = 'UPDATE_UNITS';
export const REMOVE_UNIT = 'REMOVE_UNIT';
export const REMOVE_UNITS = 'REMOVE_UNITS';
export const REMOVE_UNIT_ROW = 'REMOVE_UNIT_ROW';
