// Authentication
export const UPDATE_AUTHENTICATED = 'UPDATE_AUTHENTICATED';

// Contact actions
export const UPDATE_CONTACT_INFORMATION = 'UPDATE_CONTACT_INFORMATION';
export const REMOVE_CONTACT_INFORMATION = 'REMOVE_CONTACT_INFORMATION';

// profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';

// Notifications
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
