import _ from 'lodash';

const courseYears = [
  '1',
  '2',
  '3',
  '4',
  '5+',
];

const courseNames = [
  'Accounting & Finance',
  'Aeronautical & Manufacturing Engineering',
  'Agriculture & Forestry',
  'American Studies',
  'Anatomy & Physiology',
  'Anthropology',
  'Archaeology',
  'Architecture',
  'Art & Design',
  'Aural & Oral Sciences',
  'Biological Sciences',
  'Building',
  'Business & Management Studies',
  'Celtic Studies',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Classics & Ancient History',
  'Communication & Media Studies',
  'Complementary Medicine',
  'Computer Science',
  'Counselling',
  'Creative Writing',
  'Criminology',
  'Dentistry',
  'Drama, Dance & Cinematics',
  'East & South Asian Studies',
  'Economics',
  'Education',
  'Electrical & Electronic Engineering',
  'English',
  'Fashion',
  'Film Making',
  'Food Science',
  'Forensic Science',
  'French',
  'Geography & Environmental Sciences',
  'Geology',
  'General Engineering',
  'German',
  'History',
  'History of Art, Architecture & Design',
  'Hospitality, Leisure, Recreation & Tourism',
  'Iberian Languages/Hispanic Studies',
  'Italian',
  'Land & Property Management',
  'Law',
  'Librarianship & Information Management',
  'Linguistics',
  'Marketing',
  'Materials Technology',
  'Mathematics',
  'Mechanical Engineering',
  'Medical Technology',
  'Medicine',
  'Middle Eastern & African Studies',
  'Music',
  'Nursing',
  'Occupational Therapy',
  'Optometry, Ophthalmology & Orthoptics',
  'Pharmacology & Pharmacy',
  'Philosophy',
  'Physics and Astronomy',
  'Physiotherapy',
  'Politics',
  'Psychology',
  'Robotics',
  'Russian & East European Languages',
  'Social Policy',
  'Social Work',
  'Sociology',
  'Sports Science',
  'Theology & Religious Studies',
  'Town & Country Planning and Landscape Design',
  'Veterinary Medicine',
  'Youth Work',
  'Other',
];

const unitedKingdomUniversities = [
  'Anglia Ruskin University',
  'Arden University',
  'Arts University Bournemouth',
  'University of the Arts London',
  'Aston University',
  'University of Bath',
  'Bath Spa University',
  'University of Bedfordshire',
  'University of Birmingham',
  'University College Birmingham',
  'Birmingham City University',
  'Bishop Grosseteste University',
  'University of Bolton',
  'Bournemouth University',
  'BPP University',
  'University of Bradford',
  'University of Brighton',
  'University of Bristol',
  'Brunel University London',
  'University of Buckingham',
  'Buckinghamshire New University',
  'University of Cambridge',
  'Canterbury Christ Church University',
  'University of Central Lancashire',
  'University of Chester',
  'University of Chichester',
  'Coventry University',
  'Cranfield University',
  'University for the Creative Arts',
  'University of Cumbria',
  'De Montfort University',
  'University of Derby',
  'Durham University',
  'University of East Anglia',
  'University of East London',
  'Edge Hill University',
  'University of Essex',
  'College of Estate Management|University College of Estate Management',
  'University of Exeter',
  'Falmouth University',
  'University of Gloucestershire',
  'University of Greenwich',
  'Harper Adams University',
  'University of Hertfordshire',
  'University of Huddersfield',
  'University of Hull',
  'Imperial College London',
  'Keele University',
  'University of Kent',
  'Kingston University',
  'Lancaster University',
  'University of Law',
  'University of Leeds',
  'Leeds Arts University',
  'Leeds Beckett University',
  'Leeds Trinity University',
  'University of Leicester',
  'University of Lincoln',
  'University of Liverpool',
  'Liverpool Hope University',
  'Liverpool John Moores University',
  'University of London',
  'The London Institute of Banking & Finance|London Institute of Banking & Finance',
  'London Metropolitan University',
  'London South Bank University',
  'Loughborough University',
  'University of Manchester',
  'Manchester Metropolitan University',
  'Middlesex University',
  'Newcastle University',
  'Newman University, Birmingham|Newman University',
  'University of Northampton',
  'Northumbria University',
  'Norwich University of the Arts',
  'University of Nottingham',
  'Nottingham Trent University',
  'University of Oxford',
  'Oxford Brookes University',
  'Plymouth University',
  'University of Portsmouth',
  'University of Reading',
  'Roehampton University',
  'Royal Agricultural University',
  'University of Salford',
  'University of Sheffield',
  'Sheffield Hallam University',
  'University of Southampton',
  'Southampton Solent University',
  'University of St Mark & St John',
  'St Mary\'s University, Twickenham',
  'Staffordshire University',
  'University of Suffolk',
  'University of Sunderland',
  'University of Surrey',
  'University of Sussex',
  'Teesside University',
  'University of Warwick',
  'University of West London',
  'University of the West of England',
  'University of Westminster',
  'University of Winchester',
  'University of Wolverhampton',
  'University of Worcester',
  'Writtle University College',
  'University of York',
  'York St John University',
];

const irelandUniversities = [
  'Queen\'s University Belfast',
  'St Mary\'s University College',
  'Stranmillis University College',
  'Ulster University',
];

const scotlandUniversities = [
  'University of St Andrews',
  'University of Glasgow',
  'University of Aberdeen',
  'University of Edinburgh',
  'University of Strathclyde',
  'Heriot-Watt University',
  'University of Dundee',
  'University of Stirling',
  'Edinburgh Napier University',
  'The Robert Gordon University',
  'Glasgow Caledonian University',
  'University of Abertay Dundee',
  'Queen Margaret University',
  'University of the West of Scotland',
  'University of the Highlands and Islands',
];

const walesUniversities = [
  'Cardiff University',
  'University of South Wales',
  'Swansea University',
  'Cardiff Metropolitan University',
  'Bangor University',
  'University of Wales, Trinity Saint David',
  'Aberystwyth University',
  'Wrexham Glyndŵr University',
];

const universitiesList = _.concat(
  unitedKingdomUniversities,
  irelandUniversities,
  scotlandUniversities,
  walesUniversities,
  ['Other', 'Open University'],
);

export {
  courseYears,
  courseNames,
  universitiesList,
};

